apiVersion: v1
entries:
  locust:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2020-10-21T14:15:42.3051002+02:00"
    description: Locust helm chart
    digest: 17394f64d4f9225e866e7e1a8b6c472a07038451ebd63db413f90984a35b8b5a
    home: https://github.com/hansehe/locust
    icon: https://raw.githubusercontent.com/hansehe/locust/master/helm/locust.png
    keywords:
    - locust
    - testing
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: locust
    sources:
    - https://github.com/hansehe/locust
    type: application
    urls:
    - locust-0.1.0.tgz
    version: 0.1.0
generated: "2020-10-21T14:15:42.3051002+02:00"
