version: '3'

services:
  locust-master:
    image: hansehe/locust:${VERSION}
    hostname: locust-master
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      TARGET_HOST: ${TARGET_HOST}
    networks:
        locust-nw:
    entrypoint: locust -f locustfile.py -u ${CONCURRENT_USERS} -r ${SPAWN_RATE} --master

  locust-worker-1: &default-locust-worker
    image: hansehe/locust:${VERSION}
    environment:
      TARGET_HOST: ${TARGET_HOST}
    networks:
        locust-nw:
    entrypoint: locust -f locustfile.py --worker --master-host=locust-master

  locust-worker-2:
    <<: *default-locust-worker

  locust-worker-3:
    <<: *default-locust-worker

networks:
    locust-nw: