name: CD

on: 
  workflow_dispatch: {}
  push:
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: 
          - 3.8
        docker_version:
          - 19.09
        docker_channel:
          - stable

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup Docker
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: ${{ matrix.docker_version }}
          docker_channel: ${{ matrix.docker_channel }}
      - name: install helm
        uses: azure/setup-helm@v1
        id: install
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install requirements
        run: |
          pip install DockerBuildManagement docker-compose
      
      - name: Publish
        run: |
          dbm -build -publish service
